### ISSUE TITLE
What's up?

### ISSUE THREAD

**Issue by larsbrinkhoff** [RickCarlino/celery_forth#1]
I saw this repository created some time ago.  What's going on?  Don't leave us hanging! :-)

**Comment by RickCarlino** [comment]
Hey @larsbrinkhoff !

It's good to hear from you. I made this one a while back to explore some ideas for a problem I'm solving [at work](https://www.farm.bot).

Basically, we have a [user-definable programming language](https://software.farm.bot/docs/sequences) with an accompanying [JSON AST specification](https://github.com/FarmBot/farmbot-js/wiki/Celery-Script).

One of the problems we need to solve is _exactly_ the same problem that a Forth implementor would need to solve when implementing the `TASK` wordset. We need:

 * A virtual machine / "execution environment"
 * Preemptive multitasking for running multiple user defined "programs" in memory.
 * Pretty much all the words that come in a standard `TASK` wordset (`pause`, `signal`, `prempt` and friends)

You're absoloutely right- I _do_ need to get back to work on this one! Thanks for the encouragement.

**Comment by larsbrinkhoff** [comment]
Thanks for the info!  And good luck with Farmbot!
